### ISSUE TITLE
Push Notification Send to User Text box not serching existing user ,Having issues

### ISSUE THREAD

**Issue by dsmewara** [ijoomer-advance/ijoomer-adv-joomla#80]

**Comment by dsmewara** [comment]
Steps to reproduce the issue
![screenshot-travis-ci org 2015-05-20 14-15-02](https://cloud.githubusercontent.com/assets/11675454/7722116/db34dd00-fefa-11e4-8699-20a1378a51e5.png)
![screenshot-travis-ci org 2015-05-20 14-15-41](https://cloud.githubusercontent.com/assets/11675454/7722119/df66537c-fefa-11e4-9079-0ada660ac973.png)
![screenshot-travis-ci org 2015-05-20 14-17-22](https://cloud.githubusercontent.com/assets/11675454/7722143/10b990b0-fefb-11e4-8a3c-a4a72144f863.png)

**Comment by TasolJamal** [comment]
it's not an issue Push Notification Send to User Text box serching existing user when user register with mobile application
